pipeline {
    agent any

    environment {
        FULL_DOCKER_IMAGE_NAME = 'docker-repository.codemart.ro/tvb-gdist'
        LATEST_TAG = 'latest'
    }

    stages {
        stage ('Build docker image') {
            steps {
                script {
                    def dockerImage = docker.build("${FULL_DOCKER_IMAGE_NAME}", "-f packaging/Dockerfile packaging")
                    dockerImage.push('${LATEST_TAG}')
                }
            }
        }
        stage ('Run unit-tests') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${LATEST_TAG}'
                }
            }
            steps {
                sh '''#!/bin/bash
                    pytest --junitxml=results.xml
                    exit 0
                '''
                 junit 'results.xml'
            }
        }
        stage ('Build for Pypi') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${LATEST_TAG}'
                }
            }
            steps {
                sh '''#!/bin/bash
                    cd packaging
                    bash package_for_pip.sh
                '''
                archiveArtifacts artifacts: 'dist/*'
            }
        }
    }
    post {
        changed {
            mail to: 'lia.domide@codemart.ro',
            subject: "Jenkins Pipeline ${currentBuild.fullDisplayName} changed status",
            body: """
                Result: ${currentBuild.result}
                Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'
                Check console output at ${env.BUILD_URL}"""
        }
    }
}